import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const aeonikProBoldFont = localFont({
  src: "../../public/fonts/aeonikProTRIAL-Bold.otf",
  variable: "--font-aeonikProBold",
});

const aeonikProLight = localFont({
  src: "../../public/fonts/aeonikProTRIAL-Light.otf",
  variable: "--font-aeonikProLight",
});

const aeonikProRegular = localFont({
  src: "../../public/fonts/aeonikProTRIAL-Regular.otf",
  variable: "--font-aeonikProRegular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${aeonikProBoldFont.variable} ${aeonikProLight.variable} ${aeonikProRegular.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
