import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toast/toaster";
import StoreProvider from "@/context/store";
import React from "react";
import { OrdersProvider } from "@/context/pendingOrder";
import Guard from "@/lib/guard";
import { ThemeProvider } from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider enableSystem={true} attribute="class">
          <Guard>
            <StoreProvider>
              <OrdersProvider>{children}</OrdersProvider>
            </StoreProvider>
            <Toaster />
          </Guard>
        </ThemeProvider>
      </body>
    </html>
  );
}
